# Generated by Django 5.0.6 on 2025-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('research', 'Research Paper'), ('journal', 'Journal Article'), ('projects', 'Project')], default='journal', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
