# Generated by Django 5.0.6 on 2025-03-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_category_alter_userprofile_year_of_study'),
        ('core', 'manual_add_category'),
    ]

    operations = [
    ]
