# Generated by Django 5.0.6 on 2025-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_membershipplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('tools', 'Tools'), ('merchandise', 'Merchandise'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Feature this product on the store page'),
        ),
    ]
