# Generated by Django 5.0.6 on 2025-05-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_resourcetag_options_externalsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsite',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
