# Generated by Django 5.2.1 on 2025-05-30 12:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_externalsite_is_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='transaction_id',
            new_name='merchant_request_id',
        ),
        migrations.RenameField(
            model_name='mpesatransaction',
            old_name='description',
            new_name='result_description',
        ),
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='mpesa_receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='result_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[core.models.validate_mpesa_amount]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[core.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('card', 'Credit/Debit Card')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
