# Generated by Django 5.0.6 on 2025-06-10 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='core.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('general', 'General Engineering'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical and Electronics Engineering'), ('civil', 'Civil Engineering'), ('computer', 'Computer Science'), ('aerospace', 'Aerospace Engineering'), ('biosystems', 'Biosystems Engineering'), ('biomedical', 'Biomedical Engineering'), ('energy', 'Energy Engineering'), ('telecom', 'Telecommunications Engineering'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
