# Generated by Django 5.0.6 on 2025-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('tools', 'Tools'), ('merchandise', 'Merchandise'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
