# Generated by Django 5.0.6 on 2025-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_delivery_method_order_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
        ),
    ]
