# Generated by Django 5.0.6 on 2025-03-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='ESA-KU Store', help_text='Company or individual selling the product', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('tools', 'Tools'), ('merchandise', 'Merchandise'), ('electronics', 'Electronics'), ('software', 'Software'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
