# Generated by Django 5.0.6 on 2025-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_update_membership_test_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
