# Generated by Django 5.0.6 on 2025-07-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_membership_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='core.payment'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course',
            field=models.CharField(blank=True, help_text='Full course name', max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], null=True),
        ),
    ]
