# Generated by Django 5.0.6 on 2025-03-31 09:16

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Product = apps.get_model('core', 'Product')
    for product in Product.objects.all():
        if not product.slug:
            base_slug = slugify(product.name)
            unique_slug = base_slug
            counter = 1
            
            # Ensure slug uniqueness
            while Product.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            
            product.slug = unique_slug
            product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_vendor_alter_product_category'),
    ]

    operations = [
        migrations.RunPython(generate_slugs),
    ]
