# Generated by Django 5.0.6 on 2025-07-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_membership_payment_userprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_products', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether this product is approved for sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_user',
            field=models.ForeignKey(blank=True, help_text='User who manages this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('first_year', 'First Year Student'), ('student', 'Regular Student'), ('graduate', 'Graduate/Professional'), ('vendor', 'Vendor'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
