# Generated by Django 5.0.1 on 2025-11-11 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_approved_by_product_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin verified the payment'),
        ),
        migrations.AddField(
            model_name='membership',
            name='transaction_code',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code submitted by user', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about payment verification'),
        ),
        migrations.AddField(
            model_name='membership',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('manual', 'Manual Verification')], default='mpesa', max_length=10),
        ),
    ]
