# Generated by Django 5.0.6 on 2025-05-10 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetag',
            options={},
        ),
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('site_type', models.CharField(choices=[('university', 'University Club'), ('community', 'Community Resource'), ('partner', 'Official Partner')], max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('icon', models.CharField(blank=True, help_text="FontAwesome icon class (e.g., 'fas fa-users')", max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Site',
                'verbose_name_plural': 'External Sites',
                'ordering': ['site_type', 'name'],
            },
        ),
    ]
